version: "3"

services:
  api:
    build: .
    container_name: vtaward-api
    env_file:
      - ../envs/vtaward-api.env
    restart: always
    network_mode: host
    command:
      "yarn start:prod"
