version: "3"

services:
  api:
    build: .
    container_name: vtaward-api
    volumes:
      - "/var/www/files:/app/files"
    env_file:
      - ../envs/vtaward-api.env
    restart: always
    network_mode: host
    command:
      "yarn start"
